og_permissions_override.override.*:
  type: config_entity
  label: 'OG permission override'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    og_role:
      type: string
      label: 'OG role'
    group_entity_type:
      type: string
      label: 'Group entity type'
    group_id:
      type: integer
      label: 'Group entity ID'
    granted:
      type: sequence
      label: 'Permissions granted on this group'
      sequence:
        type: string
        label: 'Permission'
    revoked:
      type: sequence
      label: 'Permissions revoked on this group'
      sequence:
        type: string
        label: 'Permission'
